"""empty message

Revision ID: 1484f6aa4b51
Revises: 3d10aa9bdd33
Create Date: 2024-10-21 21:48:43.233811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1484f6aa4b51'
down_revision: Union[str, None] = '3d10aa9bdd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
