"""empty message

Revision ID: 1cd18d8912b4
Revises: 1484f6aa4b51
Create Date: 2024-10-21 22:06:53.798190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd18d8912b4'
down_revision: Union[str, None] = '1484f6aa4b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_username_key', 'profile', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('profile_username_key', 'profile', ['username'])
    # ### end Alembic commands ###
