"""empty message

Revision ID: 3d10aa9bdd33
Revises: a0a7c3149a42
Create Date: 2024-10-14 12:31:39.403852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d10aa9bdd33'
down_revision: Union[str, None] = 'a0a7c3149a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_link', sa.Column('sum_buys_rub', sa.Integer(), nullable=True))
    op.add_column('ref_link', sa.Column('sum_buys_stars', sa.Integer(), nullable=True))
    op.drop_column('ref_link', 'sum_buys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_link', sa.Column('sum_buys', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ref_link', 'sum_buys_stars')
    op.drop_column('ref_link', 'sum_buys_rub')
    # ### end Alembic commands ###
