"""empty message

Revision ID: 49489463de45
Revises: 937d6e34bb97
Create Date: 2024-10-12 13:49:45.731886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49489463de45'
down_revision: Union[str, None] = '937d6e34bb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('profile', sa.Column('recurring', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    op.alter_column('profile', 'recurring', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'recurring')
    # ### end Alembic commands ###
