"""empty message

Revision ID: 6c08c6336139
Revises: d46ea1c3576d
Create Date: 2024-10-04 14:20:58.300253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c08c6336139'
down_revision: Union[str, None] = 'd46ea1c3576d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('date_subscription', sa.DateTime(), nullable=True))
    op.drop_column('profile', 'update_daily_limits_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('update_daily_limits_time', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True))
    op.drop_column('profile', 'date_subscription')
    # ### end Alembic commands ###
