"""Добавляем поле is_mother в invoice

Revision ID: 937d6e34bb97
Revises: 9d8e438c9a17
Create Date: 2024-10-11 19:21:44.374067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937d6e34bb97'
down_revision: Union[str, None] = '9d8e438c9a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('is_mother', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'is_mother')
    # ### end Alembic commands ###
