"""empty message

Revision ID: a0d65b999549
Revises: 
Create Date: 2024-10-04 12:31:08.013287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d65b999549'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.Enum('FREE', 'PREMIUM', name='tariffcode'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('chatgpt_4o_daily_limit', sa.Integer(), nullable=True),
    sa.Column('chatgpt_4o_mini_daily_limit', sa.Integer(), nullable=True),
    sa.Column('midjourney_6_0_daily_limit', sa.Integer(), nullable=True),
    sa.Column('midjourney_5_2_daily_limit', sa.Integer(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('price_rub', sa.Integer(), nullable=True),
    sa.Column('price_stars', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tgid', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('url_telegram', sa.String(), nullable=True),
    sa.Column('tariff_id', sa.Integer(), nullable=True),
    sa.Column('ai_model_id', sa.String(), nullable=True),
    sa.Column('update_daily_limits_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('chatgpt_4o_daily_limit', sa.Integer(), nullable=True),
    sa.Column('chatgpt_4o_mini_daily_limit', sa.Integer(), nullable=True),
    sa.Column('mj_daily_limit_5_2', sa.Integer(), nullable=True),
    sa.Column('mj_daily_limit_6_0', sa.Integer(), nullable=True),
    sa.Column('count_request', sa.Integer(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_model.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tgid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ai_model_id', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('active_generation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_model.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Enum('STARS', 'ROBOKASSA', name='paymentname'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('hash_transaction', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_query',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('jobid', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_query',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_query')
    op.drop_table('image_query')
    op.drop_table('invoice')
    op.drop_table('chat_session')
    op.drop_table('profile')
    op.drop_table('tariff')
    op.drop_table('ai_model')
    # ### end Alembic commands ###
