"""empty message

Revision ID: dd76f073078d
Revises: 5b31100d1881
Create Date: 2024-10-14 11:04:52.287714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd76f073078d'
down_revision: Union[str, None] = '5b31100d1881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('referal_link_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile', 'ref_link', ['referal_link_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'referal_link_id')
    # ### end Alembic commands ###
